service: academy-proof-of-concept

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  getProfile:
    handler: src/handler.getProfile
    events:
      - http:
          path: profile
          method: get
          authorizer: authorise
  authorise:
    handler: src/handler.authorise